### ISSUE TITLE
Several errors after module installation

### ISSUE THREAD

**Issue by MariuszJu** [antaresproject/two_factor_auth#3]
1. I could not even install extension because of error. Please fix the configuration file: https://github.com/antaresproject/two_factor_auth/blob/master/resources/config/config.php. Valid contract for Google is `PragmaRX\Google2FA\Google2FA::class` not `PragmaRX\Google2FA\Contracts\Google2FA::class`.
2. ACL rules have not been added. There was blank page on configuration page. I had to populate database manually and grant permissions.
3. I could not configure any Authentication method because of many errors came out:

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Antares\Modules\TwoFactorAuth\Processor\UserConfigurationProcessor::isConfigured() must implement interface Antares\Area\Contracts\AreaContract, null given, called in /var/www/antares/src/modules/two_factor_auth/src/Http/Controllers/Admin/AuthController.php on line 80 in /var/www/antares/src/modules/two_factor_auth/src/Processor/UserConfigurationProcessor.php:95`

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Antares\Modules\TwoFactorAuth\Processor\AuthProcessor::verifyCredentials() must implement interface Antares\Area\Contracts\AreaContract, null given, called in /var/www/antares/src/modules/two_factor_auth/src/Http/Controllers/Admin/AuthController.php on line 103 in /var/www/antares/src/modules/two_factor_auth/src/Processor/AuthProcessor.php:90`

`Illuminate\Contracts\Container\BindingResolutionException: Target [Antares\Area\Contracts\AreaContract] is not instantiable. in /var/www/antares/vendor/laravel/framework/src/Illuminate/Container/Container.php:895`

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Antares\Modules\TwoFactorAuth\Http\Controllers\Admin\ConfigurationController::showProviderConfiguration() must implement interface Antares\Contracts\Html\Builder, instance of Antares\Area\Model\Area given, called in /var/www/antares/src/modules/two_factor_auth/src/Processor/ConfigurationProcessor.php on line 108 in /var/www/antares/src/modules/two_factor_auth/src/Http/Controllers/Admin/ConfigurationController.php:104`

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 3 passed to Antares\Modules\TwoFactorAuth\Processor\ConfigurationProcessor::edit() must be an instance of Antares\Modules\TwoFactorAuth\Model\Provider, instance of Illuminate\Database\Eloquent\Collection given, called in /var/www/antares/src/modules/two_factor_auth/src/Http/Controllers/Admin/ConfigurationController.php on line 86`

**Comment by MarcinKozak** [comment]
Not valid anymore.
