### ISSUE TITLE
Possibility of blocking login because of Two Factor

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/two_factor_auth#5]
1. Enable Two Factor for Admin Account
2. Log out from app
3. Log in -  There will be displayed two factor authentication configuration page (code to scan)
4. Click "Cancel"
5. Try to log in one more time

Results:

There is displayed "Please confirm the code below", and there is no possibility to log in, because I clicked "Cancel" on configuration step, and I don't have a verification code.

**Comment by mountstone** [comment]
@dawid-g The field of enter 2FA code will be shown after click on "Continue" button...

![image](https://user-images.githubusercontent.com/6020063/33606141-b4dbadce-d9bc-11e7-822a-d45fd9cf9bc2.png)

**Comment by dawid-g** [comment]
It's ok, closed.
