### ISSUE TITLE
Two factor auth from the custommer profile level - lang

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/two_factor_auth#6]
1. Activate Two Factor module
2. Go to admin account summary and look at "Two Factor Auth" section

Results:

There is displayed:  antares/two_factor_auth::users.manage_two_factor_auth_for_user

https://image.prntscr.com/image/C_g5wnTkS-y4z6_bUmvs6Q.png

**Comment by mountstone** [comment]
@dawid-g Fixed and available after install fresh instance

**Comment by dawid-g** [comment]
Verified as fixed.
