### ISSUE TITLE
Google Auth for Admin and User provider - "...non-object"

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/two_factor_auth#7]
1. Go to admin/settings/security
2. Select Google Auth for Admin and User provider
3. Click Submit

Results:
https://image.prntscr.com/image/P8oVOLlURnquqA1OaXKhqw.png

**Comment by mountstone** [comment]
@dawid-g Fixed and available after install fresh instance

**Comment by dawid-g** [comment]
Verified as fixed.
